triggers:
   - name: testtrigger1
     type: trigger
     version:
       counter: 78
   - name: testtrigger2
     type: trigger
     version:
    #  message: 'new teswt2'
       counter: 1
       
   - name: testruntrigger
     type: trigger
     version:
    #  message: 'new teswt2'
       counter: 2  
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
